global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
   - job_name: 'template-application'
     metrics_path: '/actuator/prometheus'
     static_configs:
        - targets: ['template-application:4000']
          labels:
            application: 'template-application'
  